### ISSUE TITLE
[1.20.1 Fabric] Crash when naming notebook

### ISSUE THREAD

**Issue by 0DeltaWaves** [JunePrimavera/Minecraft-Vanilla-Notebook#70]
[Crash log](https://api.paste.ee/p/P4NoZ)
Occurred as I was in the middle of typing a name for the notebook (which I assume is the purpose of the text entry field in the top left of the notebook UI).
This mod is so nice, hopefully these crashes can be fixed.

**Comment by JunePrimavera** [comment]
I believe this is caused by pressing space and some accessibility features thinking you've selected another button and pressed it.
It's something I have struggled to fix, other mods have done it but i'm unsure as to how currently.

**Comment by JunePrimavera** [comment]
I believe it has been fixed, though it'll take some time to get into a release.
