### ISSUE TITLE
game crashed

### ISSUE THREAD

**Issue by leolee0209** [JunePrimavera/Minecraft-Vanilla-Notebook#76]
when open the notebook, it was all empty, then the game crashed
[crash-2024-05-04_00.08.50-client.txt](https://github.com/JunePrimavera/Minecraft-Vanilla-Notebook/files/15202412/crash-2024-05-04_00.08.50-client.txt)

**Comment by JunePrimavera** [comment]
Did you update the mod from a previous version or is this a fresh install?

**Comment by leolee0209** [comment]
it was updated from beta 3.1.0. I use forge to load.

**Comment by JunePrimavera** [comment]
Follow the instructions in the readme file for updating the mod from versions prior to 4.0.0
