### ISSUE TITLE
game crashed

### ISSUE THREAD

**Issue by AnhNguyenlost13** [JunePrimavera/Minecraft-Vanilla-Notebook#77]
(I don't think this is a duplicate of #76)
(apparently there's no issue template)

Game version: 1.20.4
Mod version: 3.1.0

Clicking the red arrow button with nothing written in the book crashes the game.

[crash report](https://mclo.gs/4WqnBLA) | [client log](https://mclo.gs/jInyBMV)

Other mods are listed in the crash report.

**Comment by JunePrimavera** [comment]
Either update to v4.0.0 (Which is only on 1.20.5/1.20.6) or create an empty file - .minecraft/Notebook/Default1/0.notebookpage

v4.0.0 uses a sane system to store the book data unlike all previous versions

**Comment by AnhNguyenlost13** [comment]
so is the build unsupported?

**Comment by JunePrimavera** [comment]
Yes, there's a newer one out now

May backport to 1.20.1, but probably not 1.20.2-1.20.4
