### ISSUE TITLE
Game crash, compatibility issue

### ISSUE THREAD

**Issue by m-sarabi** [JunePrimavera/Minecraft-Vanilla-Notebook#85]
The game crashes when using it with the [No Realms Button](https://modrinth.com/mod/no-realms-button) mod.

Issue on `No Realms Button` mod: [1.21 crash](https://github.com/BluCobalt/realmsfix/issues/7)

## crash report
[crash-2024-07-29_02.56.04-client.txt](https://github.com/user-attachments/files/16452536/crash-2024-07-29_02.56.04-client.txt)

**Comment by JunePrimavera** [comment]
I can't seem to reproduce this on a fresh instance with both mods installed. Do you have the entire log leading up to the crash?

**Comment by m-sarabi** [comment]
This is the full log:
[latest.log](https://github.com/user-attachments/files/16453847/latest.log)

With only these mods (and no resource packs)
```
fabric-api-0.100.7+1.21.jar
Notebook-4.0.3.jar
realmsfix-2.0.5-SNAPSHOT.jar
```

**Comment by JunePrimavera** [comment]
It turns out I installed the wrong mod, I can reproduce the issue now and will see if I can fix it

**Comment by JunePrimavera** [comment]
I hate to ping-pong the issue but I think this is an issue with their mod rather than this one, I would imagine there's others out there which also have this bug when installed alongside looking through their mod's source

**Comment by JunePrimavera** [comment]
Found a way to make the two work together and let the other mod creator know so they can improve some things with how theirs works, so will push an update out in the next 15-20 minutes or so

**Comment by JunePrimavera** [comment]
v4.0.4+ should no longer have this issue
https://modrinth.com/mod/notebook/version/4.0.4
